"""
Write results/metrics/model_results.txt from the generated results.

Inputs (run these first):
    python evaluate.py   -> results/metrics/evaluation.csv
    python main.py       -> results/metrics/pipeline_stats.json

The original hand-written numbers are kept, unchanged, in a clearly
labelled "BEFORE FIXES" section for comparison.
"""

import json

from pathlib import Path

import pandas as pd


EVALUATION_CSV = Path("results/metrics/evaluation.csv")
PIPELINE_STATS = Path("results/metrics/pipeline_stats")
TREE_RULES = Path("results/metrics/fly_count_tree.txt")
OUTPUT = Path("results/metrics/model_results.txt")

SPLITS = [
    ("random", "random 80/20 x10"),
    ("image", "GroupKFold image"),
    ("session", "leave-1-session")
]

TASKS = [
    ("fly count", "1. FLY COUNT (per contour)",
     "DecisionTreeClassifier(max_depth=2) on contour area; label = annotated\n"
     "flies (mp/fp) inside the contour; frame count = sum over contours."),
    ("sex", "2. SEX CLASSIFICATION",
     "StandardScaler + LogisticRegression on contour area and aspect ratio."),
    ("orientation", "3. ORIENTATION (male + female)",
     "Moment axis + upright 240 px patch -> HOG -> PCA(20) ->\n"
     "LogisticRegression deciding the 180 deg flip."),
    ("wing", "4. MALE WING ANGLE",
     "Upright 288 px patch split into halves (left mirrored) -> HOG ->\n"
     "PCA(80) -> LinearRegression. Target: acute angle between mh->ma and mp->mw.")
]

# Copied verbatim from results/metrics/model_results.txt as committed in
# 55b6005 ("Update final pipeline performance"), before any fixes.
BEFORE_FIXES = """
REAL-TIME DETAILED VIDEO ANALYSIS OF FRUIT FLIES
MODEL RESULTS
===============================================

1. FLY COUNT
-------------
Model: Decision Tree Classifier
Criterion: Gini
Test Accuracy: 100.00%

Confusion Matrix:
[[9, 0, 0],
 [0, 26, 0],
 [0, 0, 36]]

Training samples: 280
Test samples: 71


2. SEX CLASSIFICATION
----------------------
Model: Logistic Regression
Preprocessing: StandardScaler
Test Accuracy: 88.46%

Confusion Matrix:
[[24, 2],
 [4, 22]]

Training samples: 204
Test samples: 52


3. ORIENTATION CLASSIFICATION
-----------------------------
Model: Logistic Regression
Preprocessing: StandardScaler + PCA
Test Accuracy: 100.00%

Confusion Matrix:
[[29, 0],
 [0, 27]]

Training samples: 221
Test samples: 56

PCA components: 4
Explained variance: 99.60%


4. MALE WING ANGLE
------------------
Model: Linear Regression
Preprocessing: StandardScaler + PCA
Mean Absolute Error (MAE): 4.24 degrees
Root Mean Squared Error (RMSE): 5.31 degrees
Standard Error: 5.25 degrees
Maximum Absolute Error: 19.31 degrees

Training samples: 411
Test samples: 103

PCA components: 4
Explained variance: 98.86%


5. VIDEO PIPELINE
-----------------
Input video: test1.mp4
Resolution: 1530 x 1530
Input FPS: 35.00
Frames processed: 351
Average processing FPS: 45.17

Output:
results/videos/final_demo.mp4
"""

WHY_BEFORE_IS_NOT_COMPARABLE = """
- Fly count: the label was min(#contours, 2) and the features were the
  sizes of those same contours, so 100% was guaranteed by construction.
- Orientation: features were distances/angles between the annotated
  head/body/abdomen keypoints, and the label came from the same points;
  at inference the pipeline fed the model placeholder constants.
- Wing angle: keypoint features included the sin/cos of the annotated
  wing direction; random split put the two wings of one image on both
  sides; inference used placeholder constants.
- Sex: same features as now, but one 52-sample test split (noisy).
- All: a single 80/20 split; orientation and wing were not grouped.
"""


def metric_table(table, task):

    subset = table[table["task"] == task]

    metrics = list(dict.fromkeys(subset["metric"]))

    width = max(len(metric) for metric in metrics) + 2

    lines = [
        " " * width + "".join(f"{name:>20}" for _, name in SPLITS)
    ]

    for metric in metrics:

        cells = []

        for split, _ in SPLITS:

            row = subset[(subset["metric"] == metric) & (subset["split"] == split)]

            if row.empty:
                cells.append(f"{'-':>20}")
            else:
                cells.append(
                    f"{row['mean'].iloc[0]:>12.1f} +- {row['std'].iloc[0]:<4.1f}"
                )

        lines.append(f"{metric:<{width}}" + "".join(cells))

    return "\n".join(lines)


def main():

    table = pd.read_csv(EVALUATION_CSV)

    all_stats = [
        json.loads(path.read_text(encoding="utf-8"))
        for path in sorted(PIPELINE_STATS.glob("*.json"))
    ]

    lines = [
        "REAL-TIME DETAILED VIDEO ANALYSIS OF FRUIT FLIES",
        "MODEL RESULTS",
        "=" * 70,
        "",
        "Generated by `python make_report.py` from",
        f"{EVALUATION_CSV} (python evaluate.py) and",
        f"{PIPELINE_STATS}/*.json (python main.py). Do not edit by hand.",
        "",
        "Values are mean +- std over folds/seeds. Columns:",
        "  random 80/20 x10  original-style random split over rows, 10 seeds",
        "  GroupKFold image  5 folds, all rows of an image held out together",
        "  leave-1-session   one recording folder held out (strictest)",
        "",
        "",
        "AFTER FIXES",
        "=" * 70
    ]

    for task, title, description in TASKS:

        lines += [
            "",
            title,
            "-" * len(title),
            description,
            "",
            metric_table(table, task)
        ]

        if task == "fly count" and TREE_RULES.exists():
            lines += ["", "Tree rules:", TREE_RULES.read_text(encoding="utf-8").strip()]

    lines += [
        "",
        "5. VIDEO PIPELINE",
        "-----------------",
        *[
            line
            for stats in all_stats
            for line in [
                f"Input video: {stats['video']} ({stats['resolution']}, "
                f"{stats['input_fps']:.0f} FPS)",
                f"  Frames processed: {stats['frames_processed']}",
                f"  Average processing FPS (read + detect + models + draw): "
                f"{stats['processing_fps']:.2f}",
                f"  Wall-clock FPS (incl. writing video"
                f"{' and preview window' if stats['display'] else ''}): "
                f"{stats['wall_clock_fps']:.2f}",
                f"  Output: {stats['output']}",
                ""
            ]
        ],
        f"Machine: {all_stats[0]['machine']}" if all_stats else "No pipeline runs found.",
        "",
        "",
        "BEFORE FIXES (original hand-written numbers, kept for comparison)",
        "=" * 70,
        "These are NOT comparable to the numbers above:",
        WHY_BEFORE_IS_NOT_COMPARABLE.strip(),
        "",
        "Original file:",
        "",
        BEFORE_FIXES.strip(),
        ""
    ]

    OUTPUT.write_text("\n".join(lines), encoding="utf-8")

    print("Written:", OUTPUT)


if __name__ == "__main__":
    main()
